config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # USERS & ADMINISTRATION
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # FROALA (WYSIWYG)
  post '/froala_upload' => 'froala#upload'
  post '/froala_manage' => 'froala#manage'
  delete '/froala_delete' => 'froala#delete'

  # HOME / root
  root to: 'site#index'
end

app/models/admin.rb
# == Schema Information
#
# Table name: admins
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_admins_on_email                 (email) UNIQUE
#  index_admins_on_reset_password_token  (reset_password_token) UNIQUE
#

class Admin < ApplicationRecord
  include RailsAdmin::AdminAdmin
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/utils.rb
module Utils
  def self.hex_to_rgba(input, alpha)
    a = ( input.match /#(..?)(..?)(..?)/ )[1..3]
    a.map!{ |x| x + x } if input.size == 4
    "rgba(#{a[0].hex},#{a[1].hex},#{a[2].hex}, #{alpha})"
  end
end

app/models/content.rb
# == Schema Information
#
# Table name: contents
#
#  id         :integer          not null, primary key
#  code       :string           not null
#  content    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_contents_on_code  (code) UNIQUE
#

class Content < ApplicationRecord
  include RailsAdmin::ContentAdmin

  validates_presence_of :code, :content
  validates_uniqueness_of :code
end

app/models/parameter.rb
# == Schema Information
#
# Table name: parameters
#
#  id         :integer          not null, primary key
#  code       :string           not null
#  value      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_parameters_on_code  (code) UNIQUE
#

class Parameter < ApplicationRecord
  include RailsAdmin::ParameterAdmin

  validates_presence_of :code, :value
  validates_uniqueness_of :code
end

app/models/seo.rb
# == Schema Information
#
# Table name: seos
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Seo < ApplicationRecord
  include RailsAdmin::SeoAdmin

  validates_presence_of :title, :description
end

app/models/seo_tool.rb
# == Schema Information
#
# Table name: seo_tools
#
#  id         :integer          not null, primary key
#  code       :string           not null
#  value      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_seo_tools_on_code  (code) UNIQUE
#

class SeoTool < ActiveRecord::Base
  include RailsAdmin::SeoToolAdmin

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  include RailsAdmin::UserAdmin
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :load_layout_data

private

  def load_layout_data
    @seo_title = Parameter.find_by_code('DEFAULT_SEO_TITLE')
    @seo_description = Parameter.find_by_code('DEFAULT_SEO_DESCRIPTION')
    @google_site_verification = SeoTool.find_by_code('GOOGLE_SITE_VERIFICATION_CODE').value
    @google_analytic = SeoTool.find_by_code('GOOGLE_ANALYTIC_CODE').value
    @google_tag_manager = SeoTool.find_by_code('GOOGLE_TAG_MANAGER_CODE').value
  end
end

app/controllers/froala_controller.rb
class FroalaController < ApplicationController
  def upload
    uploader = FroalaUploader.new(params[:model], params[:type])
    uploader.store!(params[:file])

    respond_to do |format|
      format.json { render json: {status: 'OK', link: uploader.url} }
    end
  end

  def delete
    image_name = params[:src].split('/').last

    image_path = "uploads/froala/#{params[:model]}/image/#{image_name}"
    path = "#{Rails.root}/public/#{image_path}"

    FileUtils.rm(path)

    respond_to do |format|
      format.json { render json: {status: 'OK'} }
    end
  end

  def manage
    images = []

    image_path = "uploads/froala/#{params[:model]}/image"
    real_image_path = "#{request.headers['HTTP_ORIGIN']}/uploads/froala/#{params[:model]}/image/"
    path = "#{Rails.root}/public/#{image_path}"

    if File.directory?(path)
      Dir.foreach(path) do |item|
        next if item == '.' || item == '..'
        object = ObjectImage.new
        object.url = real_image_path + item
        object.thumb = real_image_path + item
        object.tag = params[:model]

        images << object
      end
    end

    respond_to do |format|
      format.json { render json: images }
    end
  end

private

  class ObjectImage
    attr_accessor :url, :thumb, :tag
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(title)
    content_for(:title) { title }
  end

  def meta_description(meta_description)
    content_for(:meta_description) { meta_description }
  end
  
  def og_title(og_title)
    content_for(:og_title) { og_title }
  end
  
  def og_description(og_description)
    content_for(:og_description) { og_description }
  end
  
  def og_image(og_image)
    content_for(:og_image) { og_image }
  end

  def bootstrap_class_for(flash_type)
    case flash_type
    when 'success'
      'alert-success'
    when 'error'
      'alert-danger'
    when 'alert'
      'alert-warning'
    when 'notice'
      'alert-info'
    else
      flash_type.to_s
    end
  end
end

app/views/admins/shared/_links.html.erb
<% if controller_name != 'sessions' %>
  <%= link_to I18n.t 'devise.shared.links.sign_in', new_session_path(resource_name) %>
  <br/>
<% end %>
<% if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to I18n.t 'devise.shared.links.sign_up', new_registration_path(resource_name) %>
  <br/>
<% end %>
<% if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to I18n.t 'devise.shared.links.forgot_your_password', new_password_path(resource_name) %>
  <br/>
<% end %>
<% if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to I18n.t 'devise.shared.links.didn_t_receive_confirmation_instructions', new_confirmation_path(resource_name) %>
  <br/>
<% end %>
<% if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to I18n.t 'devise.shared.links.didn_t_receive_unlock_instructions', new_unlock_path(resource_name) %>
  <br/>
<% end %>
<% if devise_mapping.omniauthable? %>
  <% resource_class.omniauth_providers.each do |provider| %>
    <%= link_to I18n.t('devise.shared.links.sign_in_with_provider', provider: OmniAuth::Utils.camelize(provider)), omniauth_authorize_path(resource_name, provider) %>
    <br/>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= yield(:title).present? ? yield(:title) : @seo_title.value %></title>
    <meta name="description" content="<%= yield(:meta_description).present? ? yield(:meta_description) : @seo_description.value %>">
    <%= favicon_link_tag 'favicon.png', type: 'image/png' %>
    <meta property="og:url"           content="<%= request.original_url %>" />
    <meta property="og:type"          content="website" />
    <meta property="og:title"         content="<%= yield(:og_title).present? ? yield(:og_title) : @seo_title.value %>" />
    <meta property="og:description"   content="<%= yield(:og_description).present? ? yield(:og_description) : @seo_description.value %>" />
    <meta property="og:image"         content="<%= yield(:og_image).present? ? yield(:og_image) : asset_url('logo-og.jpg') %>" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <% if @google_site_verification.present? %>
        <meta name="google-site-verification" content="<%= @google_site_verifcation %>" />
    <% end %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto" rel="stylesheet">
    <meta name="turbolinks-cache-control" content="no-cache">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <%= javascript_include_tag 'ie' %>
    <![endif]-->
    <% if @google_analytic.present? %>
        <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function () {
                        (i[r].q = i[r].q || []).push(arguments)
                    }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                    m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

            ga('create', '<%= @google_analytic %>', 'auto');
            ga('send', 'pageview');
        </script>
    <% end %>
    <% if @google_tag_manager.present? %>
        <script>
            (function (w, d, s, l, i) {
                w[l] = w[l] || [];
                w[l].push({
                    'gtm.start': new Date().getTime(), event: 'gtm.js'
                });
                var f = d.getElementsByTagName(s)[0],
                    j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
                j.async = true;
                j.src =
                    'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
                f.parentNode.insertBefore(j, f);
            })(window, document, 'script', 'dataLayer', '<%= @google_tag_manager %>');
        </script>
    <% end %>
  </head>
  <body>
    <% if @google_tag_manager.present? %>
      <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=<%= @google_tag_manager %>" height="0" width="0" style="display:none;visibility:hidden"></iframe>
      </noscript>
    <% end %>
    <%= render partial: 'shared/flash_messages', flash: flash %>
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
  <title>Administration</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" type="text/css"/>
</head>
<body>
<div class="devise">
  <%= yield %>
</div>
</body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= message %>
  </div>
<% end %>

app/views/site/index.html.erb
<div class="container-fluid">
  <div class="rollinbox">
    <div class="rounded">
      <i class="fa fa-rocket icon-centered"></i>
    </div>
  </div>
</div>